/*
SELECT REF 
SELECT DEREF 
CONSULTA À VARRAY 
CONSULTA À NESTED TABLE 
*/

/*TABELAS
 CLIENTE FUNCIONARIO
 NUTRICIONISTA FABRICANTE 
 
 CONSULTA MARCAR CONSULTA LEAL 
 VENDEDOR ATENDENTE  RODRIGO
 COMPRA PRODUTO  WELISSON
*/